site_name: Tracetest
site_description: "Tracetest - Trace based testing.  Leverage your investment in tracing to easily create integration tests."
site_author: "Kubeshop Tracetest Team"
docs_dir: docs/
repo_name: "kubeshop/tracetest"
repo_url: "https://github.com/kubeshop/tracetest"
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  features:
    - navigation.expand

nav:
  - Welcome: index.md
  - Concepts:
    - Introduction to Trace-Based Testing: introduction.md
    - Architecture: architecture.md
    - Specifying Selectors: advanced-selectors.md
  - Getting Started:
    - Supported Backends: supported-backends.md
    - Installation: installing.md
    - Accessing Tracetest Dashboard: accessing-dashboard.md
  - Using Tracetest:
    - Creating Tests: create-test.md
    - Test Results: test-results.md
    - Adding Test Specifications: adding-assertions.md
    - Versioning: versioning.md
  - Command Line Interface:
    - Command Line Tool: command-line-tool.md
    - Test Definition File: test-definition-file.md
  - Automating Tests for CI/CD:
    - CI/CD Best practices: ci-cd-best-practices.md
  - OpenAPI Definition: openapi.md
  - Installable Example - Pokeshop Service:
      - Overview: pokeshop.md
      - Add Pokemon Endpoint: pokeshop/add-pokemon.md
      - Import Pokemon Endpoint: pokeshop/import-pokemon.md
      - List Pokemon Endpoints: pokeshop/list-pokemon.md

extra:
  analytics:
    provider: google
    property: UA-204665550-9

  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - render_swagger
  - search

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - css/extra.css
extra_javascript:
  - https://unpkg.com/mermaid@9.1.3/dist/mermaid.min.js

copyright: Copyright &copy; 2022 <a href="https://kubeshop.io">Kubeshop</a>
