site_name: Tracetest
site_description: "Tracetest - Trace based testing.  Leverage your investment in tracing to easily create integration tests."
site_author: "Kubeshop Tracetest Team"
docs_dir: docs/
repo_name: "kubeshop/tracetest"
repo_url: "https://github.com/kubeshop/tracetest"
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  #logo: img/logo.png
  #favicon: img/favicon.ico
  features:
    - navigation.expand

extra_css:
  - css/extra.css

nav:
  - Welcome: index.md
  - Introduction: introduction.md
    - Architecture: architecture.md
  - Getting Started: 
    - Installation: installing.md
    - Accessing Tracetest Dashboard: accessing-dashboard.md
  - Using Tracetest:
    - Creating Tests: create-test.md
    - Adding Assertions: adding-assertions.md
    - Versioning: versioning.md
  - Automating Tests for CI/CD:
    - Command Line Tool: command-line-tool.md
    - Test Definition File: test-definition-file.md
    - Specifying Selectors: advanced-selectors.md
    - CI/CD Best practices: ci-cd-best-practices.md
  - OpenAPI Definition: openapi.md
  - Development: development.md
  - Installable example - Pokeshop Service:
      - Overview: pokeshop.md
      - Add Pokemon Endpoint: pokeshop/add-pokemon.md
      - Import Pokemon Endpoint: pokeshop/import-pokemon.md
      - List Pokemon Endpoints: pokeshop/list-pokemon.md  

extra:
  analytics:
    provider: google
    property: G-175WMKCFBZ

  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - render_swagger
  - search

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  # - pymdownx.superfences:
  #     # make exceptions to highlighting of code:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@9.1.3/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@9.1.3/dist/mermaid.min.js

copyright: Copyright &copy; 2022 <a href="https://kubeshop.io">Kubeshop</a>
