---
postgresConnString: "host=tt_postgres user=postgres password=postgres port=5432 sslmode=disable"

poolingConfig:
  maxWaitTimeForTrace: 30s
  retryDelay: 500ms

demo:
  enabled: [otel]
  endpoints:
    otelFrontend: http://frontend:8080
    otelProductCatalog: productcatalogservice:3550
    otelCart: cartservice:7070
    otelCheckout: checkoutservice:5050

experimentalFeatures: []

googleAnalytics:
  enabled: false

telemetry:
  dataStores:
    otlp:
      type: otlp

  exporters:
    collector:
      serviceName: tracetest
      sampling: 100
      exporter:
        type: collector
        collector:
          endpoint: otelcol:4317

server:
  telemetry:
    dataStore: otlp
    exporter: collector
    applicationExporter: collector
