postgres:
  host: postgres
  user: postgres
  password: postgres
  port: 5432
  dbname: tracetest
  params: sslmode=disable

poolingConfig:
  maxWaitTimeForTrace: 10m
  retryDelay: 5s

googleAnalytics:
  enabled: true

telemetry:
  dataStores:
    jaeger:
      type: jaeger
      jaeger:
        endpoint: jaeger:16685
        tls:
          insecure: true

server:
  telemetry:
    dataStore: jaeger
