type: Environment
spec:
  id: .env
  name: .env
  description: ""
  createdAt: 2023-06-07T14:32:36.664453Z
  values:
  - key: FIRST_VAR
    value: some-value
  - key: SECOND_VAR
    value: updated_value
  - key: THIRD_VAR
    value: hello
