postgres:
  host: postgres
  user: postgres
  password: postgres
  port: 5432
  dbname: postgres
  params: sslmode=disable

poolingConfig:
  maxWaitTimeForTrace: 10m
  retryDelay: 5s

googleAnalytics:
  enabled: true

demo:
  enabled: []

experimentalFeatures: []

telemetry:
  dataStores:
    tempo:
      type: tempo
      tempo:
        endpoint: tempo:9095
        tls:
          insecure: true

server:
  telemetry:
    dataStore: tempo
    exporter: collector
    applicationExporter: collector
