---
postgresConnString: "host=tt-postgres user=postgres password=postgres port=5432 sslmode=disable"

poolingConfig:
  maxWaitTimeForTrace: 30s
  retryDelay: 500ms

demo:
  enabled: [otel]
  endpoints:
    otelFrontend: http://otel-frontend:8084
    otelProductCatalog: otel-productcatalogservice:3550
    otelCart: otel-cartservice:7070
    otelCheckout: otel-checkoutservice:5050

experimentalFeatures: []

googleAnalytics:
  enabled: true

telemetry:
  dataStores:
    otlp:
      type: otlp

  exporters:
    collector:
      serviceName: tracetest
      sampling: 100
      exporter:
        type: collector
        collector:
          endpoint: otel-collector:4317

server:
  telemetry:
    dataStore: otlp
    exporter: collector
    applicationExporter: collector
